@startuml
hide empty description
[*] --> openingTag : <html>
openingTag ---> inTagName : <head> chars[index-1]=='<'
openingTag ---> inComment : <!--[if !IE]><!--> chars[index]=='!'&&chars[index+1]=='-'&&chars[index+2]=='-'
openingTag ---> inDoctype : <!DOCTYPE html> chars[index]=='!'&& DOCTYPE

inTagName ---> inAttribute : <head data> chars[index]==' '
inTagName ---> openTagClosing : <head> chars[index]=='>'

inComment ---> literal : -->aaaa</body>  chars[index-1]=='>'&&chars[index-2]=='-'&&chars[index-3]=='-'&&chars[index]!='<'
inComment ---> openingTag : --></body>  chars[index-1]=='>'&&chars[index-2]=='-'&&chars[index-3]=='-'&&chars[index]=='<'
inComment ---> closingTag : --></body>  chars[index-1]=='>'&&chars[index-2]=='-'&&chars[index-3]=='-'&&chars[index]=='<'

inDoctype ---> openTagClosing : <!DOCTYPE html> chars[index]=='>'

inAttribute ---> openTagClosing : <head> chars[index]=='>'

openTagClosing ---> inTextContent : <body>sdd chars[index-1]='>'&&chars[index]!='<'
openTagClosing ---> openingTag : <br/><a> chars[index]=='<'
openTagClosing ---> closingTag : <p></p> chars[index]=='<'&&chars[index]=='/'

inTextContent ---> closingTag : <body>sdd</body> chars[index]=='<'&&chars[index[index+1]]=='/'
inTextContent ---> openingTag : <body>sdd<p> chars[index]=='<'

closingTag ---> openTag : </body><a> chars[index]=='<'
closingTag ---> closingTag : </body></html> chars[index]=='<'&&chars[index+1]=='/'
closingTag ---> literal : </body>aaa</html> chars[index-1]=='>'&&chars[index]!='<'
closingTag ---> [*]

literal ---> openTag : </body>hahaha<a> chars[index]=='<'
literal ---> closingTag : </body>hahaha</html> chars[index]=='<'&&chars[index+1]=='/'

@enduml